export const courses = [
  {
    id: 1,
    title: "Web Development",
    description: "Learn HTML, CSS, JavaScript",
    lessons: 20,
    duration: "2 Months",
    price: "LKR 5000",
    instructor: "John Silva",
  },
  {
    id: 2,
    title: "Java Programming",
    description: "Master Java from beginner to advanced",
    lessons: 25,
    duration: "3 Months",
    price: "LKR 6000",
    instructor: "Anjali Perera",
  },
  {
    id: 3,
    title: "Database Design",
    description: "Learn MySQL and database concepts",
    lessons: 18,
    duration: "6 Weeks",
    price: "LKR 4500",
    instructor: "Nimal Fernando",
  },
  {
    id: 4,
    title: "React JS",
    description: "Build modern web applications using React",
    lessons: 22,
    duration: "2 Months",
    price: "LKR 7000",
    instructor: "Hasini Jayasuriya",
  },
  {
    id: 5,
    title: "UI/UX Design",
    description: "Learn modern app & web design principles",
    lessons: 16,
    duration: "5 Weeks",
    price: "LKR 4800",
    instructor: "Sachini Silva",
  },
  {
    id: 6,
    title: "Python Programming",
    description: "Start coding with Python from basics",
    lessons: 24,
    duration: "2 Months",
    price: "LKR 6500",
    instructor: "Dinesh Perera",
  },
];
